server:
  port: 8080
  error:
    include:
      message: true

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    net.devh.boot.grpc: INFO
#    org.springframework.boot.autoconfigure: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'
  graphql:
    graphiql:
      enabled: true

grpc:
  client:
    userdataClient:
      address: 'static://localhost:8091'
      negotiationType: PLAINTEXT
    geoClient:
      address: 'static://localhost:8092'
      negotiationType: PLAINTEXT
    photoClient:
      address: 'static://localhost:8093'
      negotiationType: PLAINTEXT

rangiffler-front:
  base-uri: 'http://127.0.0.1:3001'
---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://auth.rangiffler.dc:9000'
  graphql:
    graphiql:
      enabled: true

grpc:
  client:
    userdataClient:
      address: 'static://userdata.rangiffler.dc:8091'
      negotiationType: PLAINTEXT
    geoClient:
      address: 'static://geo.rangiffler.dc:8092'
      negotiationType: PLAINTEXT
    photoClient:
      address: 'static://photo.rangiffler.dc:8093'
      negotiationType: PLAINTEXT

rangiffler-front:
  base-uri: 'http://frontend.rangiffler.dc'
---