version: '3.9'

services:
  rangiffler-mysql:
    container_name: rangiffler-mysql
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
#    volumes:
#      - rangiffler-all-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
    expose:
      - "3306"
    networks:
      - test-network
    dns_search: .

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    expose:
      - "2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - test-network

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    expose:
      - "9092"
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
    networks:
      - test-network

  auth.rangiffler.dc:
    container_name: auth.rangiffler.dc
    image: ${PREFIX}/rangiffler-auth-${PROFILE}:latest
    ports:
      - "9000:9000"
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health || exit 1"
      interval: 15s
      timeout: 15s
      retries: 10
    restart: always
    depends_on:
      rangiffler-mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - test-network
    dns_search: .

  gateway.rangiffler.dc:
    container_name: gateway.rangiffler.dc
    image: ${PREFIX}/rangiffler-gateway-${PROFILE}:latest
    ports:
      - "8080:8080"
    healthcheck:
      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    depends_on:
      auth.rangiffler.dc:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  geo.rangiffler.dc:
    container_name: geo.rangiffler.dc
    image: ${PREFIX}/rangiffler-geo-${PROFILE}:latest
    expose:
      - "8092"
    restart: always
    depends_on:
      auth.rangiffler.dc:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  photo.rangiffler.dc:
    container_name: photo.rangiffler.dc
    image: ${PREFIX}/rangiffler-photo-${PROFILE}:latest
    expose:
      - "8093"
    restart: always
    depends_on:
      auth.rangiffler.dc:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  userdata.rangiffler.dc:
    container_name: userdata.rangiffler.dc
    image: ${PREFIX}/rangiffler-userdata-${PROFILE}:latest
    expose:
      - "8091"
    restart: always
    depends_on:
      auth.rangiffler.dc:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  frontend.rangiffler.dc:
    container_name: frontend.rangiffler.dc
    image: "${FRONT_IMAGE}"
    ports:
      - "80:80"
    restart: always
    depends_on:
      gateway.rangiffler.dc:
        condition: service_healthy
    networks:
      - test-network
    dns_search: .

  selenoid:
    container_name: selenoid
    image: aerokube/selenoid:1.11.2
    platform: "${ARCH}"
    volumes:
      - ./selenoid:/etc/selenoid
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [ "-conf", "/etc/selenoid/browsers.json", "-limit", "3", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs", "-container-network", "rangiffler_test-network" ]
    ports:
      - "4444:4444"
    networks:
      - test-network
    dns_search: .

  selenoid-ui:
    container_name: selenoid-ui
    image: aerokube/selenoid-ui:1.10.11
    depends_on:
      - selenoid
    restart: unless-stopped
    ports:
      - "9090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - test-network
    dns_search: .

  rangiffler-tests:
    container_name: rangiffler-tests
    image: ${PREFIX}/rangiffler-tests:latest
    environment:
      ALLURE_DOCKER_API: http://allure:5050
      TEST_ENV: docker
    depends_on:
      selenoid:
        condition: service_started
      frontend.rangiffler.dc:
        condition: service_started
    volumes:
      - allure-artifacts:/rangiffler/rangiffler-tests/build/allure-results/
    networks:
      - test-network
    dns_search: .

  allure:
    container_name: allure
    image: frankescobar/allure-docker-service
    depends_on:
      - rangiffler-tests
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 3
      KEEP_HISTORY: 0
    volumes:
      - allure-artifacts:/app/allure-results
    ports:
      - "5050:5050"
    networks:
      - test-network
    dns_search: .

  allure-ui:
    container_name: allure-ui
    image: frankescobar/allure-docker-service-ui:7.0.3
    depends_on:
      - allure
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: http://allure:5050
    ports:
      - "5252:5252"
    networks:
      - test-network
    dns_search: .
volumes:
  allure-artifacts:
    name: rangiffler-allure-artifacts
#  rangiffler-all-db:
#    external: true

networks:
  test-network:
    driver: bridge