grpc:
  server:
    port: 8092
spring:
  application:
    name: rangiffler-geo
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    schemas: rangiffler-geo
    locations: classpath:db/migration/rangiffler-geo
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    open-in-view: false
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.flywaydb.core: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  datasource:
    url: 'jdbc:mysql://localhost:3306/rangiffler-geo?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
---
spring:
  config:
    activate:
      on-profile: 'docker'
  datasource:
    url: 'jdbc:mysql://rangiffler-mysql:3306/rangiffler-geo?serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
---